package vista.factura;

import controlador.FacturaController;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import modelo.FacturaModel;
import modelo.entidades.Cliente;
import modelo.entidades.Factura;
import vista.AbstractViewImpl;
import vista.cliente.ClienteTableAndComboModel;

public class FacturaViewImpl extends AbstractViewImpl<FacturaController> implements FacturaView {

    private FacturaTableModel facturaTableModel;
    private FacturaViewImplInternal panelFactura;
    private ClienteTableAndComboModel clienteComboModel;

    public FacturaViewImpl() {
        facturaTableModel = new FacturaTableModel();
        //comboModel = new ClienteTableAndComboModel();
        clienteComboModel = ClienteTableAndComboModel.create();
        initComponents();

        this.panelFactura = new FacturaViewImplInternal(this);
        this.jPanelFactura.add(this.panelFactura);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFacturas = new javax.swing.JTable();
        jPanelFactura = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonFiltrar = new javax.swing.JButton();
        jButtonQuitarFiltro = new javax.swing.JButton();
        jTextFieldFiltro = new javax.swing.JTextField();

        jTableFacturas.setModel(facturaTableModel);
        jTableFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFacturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFacturas);

        jPanelFactura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelFactura.setLayout(new javax.swing.BoxLayout(jPanelFactura, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Fecha");

        jButtonFiltrar.setText("Filtrar");
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarActionPerformed(evt);
            }
        });

        jButtonQuitarFiltro.setText("QuitarFiltro");
        jButtonQuitarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarFiltroActionPerformed(evt);
            }
        });

        jTextFieldFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButtonFiltrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldFiltro)
                            .addComponent(jButtonQuitarFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonFiltrar)
                            .addComponent(jButtonQuitarFiltro))))
                .addGap(18, 18, 18)
                .addComponent(jPanelFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFacturasMouseClicked
        FacturaTableModel ctm = (FacturaTableModel) this.jTableFacturas.getModel();
        Factura factura = ctm.getRow(this.jTableFacturas.getSelectedRow());
        panelFactura.setFactura(factura);
    }//GEN-LAST:event_jTableFacturasMouseClicked

    private void jButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarActionPerformed
        List<Factura> facturas = getController().listarFacuraEntidadPorFecha(this.jTextFieldFiltro.getText());
        facturaTableModel.setFacturas(facturas);
        /*
        ClienteTableAndComboModel ccm=(ClienteTableAndComboModel)this.jComboBoxCliente.getModel();
        Cliente cliente= ccm.getRow(this.jComboBoxCliente.getSelectedIndex());
        List<Factura> facturas=getController().listarFacuraEntidadPorClienteGesture(cliente.getDNI());
        facturaTableModel.setFacturas(facturas);
         */
    }//GEN-LAST:event_jButtonFiltrarActionPerformed

    private void jButtonQuitarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarFiltroActionPerformed
        refresh();
    }//GEN-LAST:event_jButtonQuitarFiltroActionPerformed

    private void jTextFieldFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFiltroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonQuitarFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFactura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFacturas;
    private javax.swing.JTextField jTextFieldFiltro;
    // End of variables declaration//GEN-END:variables

    protected ClienteTableAndComboModel getComboModel() {
        return clienteComboModel;
    }

    public void refresh() {
        facturaTableModel.setFacturas(getController().listaFacturaEntidadGesture());//cambia el modelo de JTable(TableModel) por medio de una clase que hemos creado (ContactosTableModel)
    }

    protected void fireNuevaFacturaGesture(String identificador, Cliente cliente, String importe, String fecha) {
        List<Serializable> datos = new ArrayList<Serializable>();
        datos.add(identificador);
        datos.add(cliente);
        datos.add(importe);
        datos.add(fecha);
        getController().nuevaEntidadGesture(datos);
    }

    protected void fireActualizaFacturaGesture(String identificador, Cliente cliente, String importe, String fecha) {
        List<Serializable> datos = new ArrayList<Serializable>();
        datos.add(identificador);
        datos.add(cliente);
        datos.add(importe);
        datos.add(fecha);
        getController().actualizaEntidadGesture(datos);
    }

    protected void fireBorraFacturaGesture(String identificador) {
        getController().borraEntidadGesture(identificador);
    }
}
